# nixpacks.toml

# Especifica las fases del proceso de construcción
[phases.setup]
nixPkgs = ['nodejs', 'yarn']  # Instala Node.js y Yarn

[phases.install]
cmds = ['yarn install']  # Instala las dependencias del proyecto usando Yarn

[phases.build]
cmds = ['yarn build']  # Construye la aplicación de React

# Define cómo debe iniciarse la aplicación
[start]
cmd = 'serve -s build -l 3000'  # Sirve la aplicación React construida desde la carpeta 'build' en el puerto 3000
