[variables]
    NPM_CONFIG_UPDATE_NOTIFIER = 'false'
    NPM_CONFIG_FUND = 'false'
  
[start]
    runImage = 'node:18'
    workDir = '/'
    onlyIncludeFiles = ['package.json', 'webpack.config.js', 'public', '.eslintignore', 'cypress.config.js', 'README.md', 'test', '.gitignore', 'ci-test', 'eslint.config.mjs', '.gitattributes', '.babelrc', '.eslintrc.js', 'src', 'cypress', '.github', 'package-lock.json']
    cmd = 'npm run build && npm run start'