# https://nixpacks.com/docs/configuration/file

# set up some variables to minimize annoyance
[variables]
    NPM_CONFIG_UPDATE_NOTIFIER = 'false' # the update notification is relatively useless in a production environment
    NPM_CONFIG_FUND = 'false' # the fund notification is also pretty useless in a production environment
  
# copy caddy and build artifacts to a new image and start the caddy web server
[start]
    runImage = 'node:18' # Usar la imagen de Node.js 18 como base
    onlyIncludeFiles = ['app.js', 'package.json', 'dist'] # Copiar solo los archivos necesarios para la ejecución de la aplicación
    cmd = 'node app.js' # Comando para iniciar la aplicación
    # Configuración para la fase de construcción (build)

[build]
    builder = 'NIXPACKS' # Usar Nixpacks para la construcción
    watchPatterns = ['dist'] # Observar cambios en el directorio 'dist' para la reconstrucción
