[variables]
    NPM_CONFIG_UPDATE_NOTIFIER = 'false'
    NPM_CONFIG_FUND = 'false'
  
[start]
    runImage = 'node:18'
    workDir = '/'
    onlyIncludeFiles = ['app.js', 'package.json', 'dist']
    cmd = 'node app.js'

[build]
    builder = 'NIXPACKS'
    watchPatterns = ['dist']
