# railway.toml

[build]
builder = "npm"
buildCommand = "npm install && npm run build"

[deploy]
startCommand = "serve -s -n -L -p $PORT dist"
healthcheckPath = "/"
healthcheckTimeout = 100
restartPolicyType = "never"
